### ISSUE TITLE
请问后续还会继续更新吗？

### ISSUE THREAD

**Issue by wajika** [StabilityMan/StabilityGuide#15]
很喜欢《让可观察性带上导航，快速发现和定位业务问题：OpenTracing上写入业务信息》这篇文章，可惜好几年没更新了。

**Comment by StabilityMan** [comment]
最近正在跟各位作者约稿，近期会更新的

**Comment by wajika** [comment]
> 最近正在跟各位作者约稿，近期会更新的

能分享你们公司的可靠性工程建设思路吗

**Comment by StabilityMan** [comment]
这个话题有点大，可以先参考虾米 SRE 和饿了么监控这两篇文章，后续有机会我会根据自己的理解也整理一篇。

**Comment by wajika** [comment]
> 这个话题有点大，可以先参考虾米 SRE 和饿了么监控这两篇文章，后续有机会我会根据自己的理解也整理一篇。

我觉得议题可以很多，比如说数据库可靠性工程怎么做，服务的可靠性工程怎么实现，能分享些你们的思路和解决方案就可以了，不需要太精致，先把量上来。

**Comment by StabilityMan** [comment]
嗯，我们后面会从技术解读和特定领域最佳实践（如K8S，数据库，Redis）两个方向来沉淀。 好文章难求，欢迎一起参与共建！
