### ISSUE TITLE
良好的技术和架构设计是最好的事前防范

### ISSUE THREAD

**Issue by winjeg** [StabilityMan/StabilityGuide#18]
在事前防范方面， 最重要的还是一个好的架构设计， 如果架构很烂， 那么，这个系统出问题的频次肯定会比较高。

**Comment by StabilityMan** [comment]
赞同，如果在设计阶段就没有考虑高可用等因素，后续改造的成本会非常，存量用户的历史包袱会令人崩溃。比如同城/异地多活，多租户数据隔离，消息队列缓冲等。  所以，我们在启动一个新项目的方案评审时，都需要有相应的系统架构图。

如果有好的架构设计文章，非常欢迎提交 PR~
