### ISSUE TITLE
部署成在线文档站

### ISSUE THREAD

**Issue by eryajf** [StabilityMan/StabilityGuide#19]
如果能够将专栏部署成一个在线文档站，会更加正式，也易于阅读一些。

**Comment by StabilityMan** [comment]
非常好的建议，捣鼓了半天，终于部署了一个简易的文档站，快来试用看看吧！ https://stabilityman.github.io/

**Comment by eryajf** [comment]
说实话，感觉这个站点呈现的风格，不够直观，对于知识呈现也是有很大损毁的，你可以看下我的这个程序官方文档站：http://ldapdoc.eryajf.net/  也是可以直接静态部署到GitHub Page 的

**Comment by StabilityMan** [comment]
嗯嗯，你这个文档站看起来很棒！结构清晰，看起来很舒服。后面找时间我再优化一下，目前这个确实比较粗糙~

**Comment by eryajf** [comment]
> 嗯嗯，你这个文档站看起来很棒！结构清晰，看起来很舒服。后面找时间我再优化一下，目前这个确实比较粗糙~

我做了一个模板，基于此模板，只需要简单三步配置，就可以构建一个优雅美观的博客。

模板地址：https://github.com/eryajf/vdoing-template
