### ISSUE TITLE
此处有笔误

### ISSUE THREAD

**Issue by xutongd** [StabilityMan/StabilityGuide#2]
https://github.com/StabilityMan/StabilityGuide/blob/master/docs/diagnosis/jvm/exception/%E7%B3%BB%E7%BB%9F%E7%A8%B3%E5%AE%9A%E6%80%A7%E2%80%94%E2%80%94OutOfMemoryError%E5%B8%B8%E8%A7%81%E5%8E%9F%E5%9B%A0%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95.md#7-kill-process-or-sacrifice-child

然后将评分较低的进程“杀死”---应该是评分较高的进程会被"杀死"

**Comment by StabilityMan** [comment]
嗯嗯，确实是评分高的会优先被 Kill，多谢指正，马上修改！~

**Comment by StabilityMan** [comment]
已修正，并添加了一个图例，便于理解 OOM Killer 的现象。再次感谢指正~
